### ISSUE TITLE
Volunteer job overlap triggers when Volunteer has no jobs

### ISSUE THREAD

**Issue by Saerith** [Saerith/TCSS360Group3#11]
The Volunteer class's check of the business rule that no jobs must overlap throws a volunteerJobOverlapException even when the volunteer has no jobs in their jobsList.

**Comment by walkhh** [comment]
Oh, that can be fixed by swapping true/false in doesNewJobOverlap. What branch should I put this fix on?

**Comment by Saerith** [comment]
Oh, you can commit straight back to this branch, then we can merge all together.

**Comment by walkhh** [comment]
Fixed, probably (can't run program yet so can't tell)

**Comment by walkhh** [comment]
Shit I committed to master by mistake. Sorry

**Comment by Saerith** [comment]
It's okay, I have it working (except for one formatting thing) and I'll be submitting a PR shortly. If it's not merged tomorrow morning I'll use what I've got to demo.
