### ISSUE TITLE
As a Park Manager I want to view the future jobs that I have submitted

### ISSUE THREAD

**Issue by Saerith** [Saerith/TCSS360Group3#22]

**Comment by abderisaq** [comment]
These are the changes that I made:

(1) Job class

Added this method to check if the job starts today or in the future:
isInFuture()

(2) ParkManager class

Added a new method to test if the given job was created by the park manager:
isCreatedJob(Job theJob)

(3) JobCollection class:

Added a new method to return all jobs that in the future and created by the park manager:
getAvilableJobs(ParkManager parkManager)
