### ISSUE TITLE
As a User I want to be identified by the system

### ISSUE THREAD

**Issue by Saerith** [Saerith/TCSS360Group3#23]
Rule:
No User can carry out any other user story until they are identified by the system

Rule:
A user must be one of Urban Parks Staff Member, Park Manager, or Volunteer

**Comment by vekk513** [comment]
What is there missing from this user story that is not currently in our program? I can finish up whatever is left.

**Comment by Saerith** [comment]
As far as I can tell, this is already baked into our deliverable 2 in the terminal UI. Unless you can think of anything, I'm going to close it for now.
