### ISSUE TITLE
Job should store a list of its volunteers

### ISSUE THREAD

**Issue by Saerith** [Saerith/TCSS360Group3#26]
A job should store a list of the volunteers that are currently signed up for it.
This means that there is a 2-way relationship between jobs and volunteers.
When volunteers and jobs are associated, both references MUST be changed, or they will become unsynced, which will require some refactoring.

**Comment by walkhh** [comment]
Alternative: When a job is cancelled we can set its cancelled flag to true, then when a volunteer lists jobs, that job won't be displayed (or any other visual indicator)

**Comment by vekk513** [comment]
This has been created and merged I believe, closing for now.
