### ISSUE TITLE
Handle lowering max pending jobs to under the current number of pending jobs

### ISSUE THREAD

**Issue by walkhh** [Saerith/TCSS360Group3#45]
This should be handled gracefully. Either:
Don't let urban parks staff do this, or
Shrink the number of pending jobs to the new value

**Comment by vekk513** [comment]
My vote is for don't let them do it, but I'm curious if there as an advantage to the second.

**Comment by walkhh** [comment]
I'll implement #1 shortly mainly because it will beway easier to program.
